import type { StageData } from "../types.js";

export const pocStage: StageData = {
  id: "poc-01",
  name: "PoCステージ",
  budget: 5_000_000,
  deadline: 22,
  initialMembers: [
    { id: "alice", name: "アリス", skill: 12, exp: 0, morale: 100, health: 100 },
    { id: "bob", name: "ボブ", skill: 8, exp: 0, morale: 100, health: 100 },
    { id: "carol", name: "キャロル", skill: 6, exp: 0, morale: 100, health: 100 },
  ],
  initialGantt: {
    tasks: [
      {
        id: "t01",
        name: "要件定義",
        phase: "要件定義",
        startTurn: 1,
        duration: 3,
        assignedMemberId: "alice",
        progress: 0,
        status: "active",
        dependencies: [],
      },
      {
        id: "t02",
        name: "UI設計",
        phase: "設計",
        startTurn: 4,
        duration: 3,
        assignedMemberId: "alice",
        progress: 0,
        status: "active",
        dependencies: ["t01"],
      },
      {
        id: "t03",
        name: "DB設計",
        phase: "設計",
        startTurn: 4,
        duration: 2,
        assignedMemberId: "bob",
        progress: 0,
        status: "active",
        dependencies: ["t01"],
      },
      {
        id: "t04",
        name: "API実装",
        phase: "実装",
        startTurn: 7,
        duration: 5,
        assignedMemberId: "alice",
        progress: 0,
        status: "active",
        dependencies: ["t02", "t03"],
      },
      {
        id: "t05",
        name: "フロント実装",
        phase: "実装",
        startTurn: 7,
        duration: 5,
        assignedMemberId: "carol",
        progress: 0,
        status: "active",
        dependencies: ["t02"],
      },
      {
        id: "t06",
        name: "バックエンド実装",
        phase: "実装",
        startTurn: 7,
        duration: 4,
        assignedMemberId: "bob",
        progress: 0,
        status: "active",
        dependencies: ["t03"],
      },
      {
        id: "t07",
        name: "単体テスト",
        phase: "テスト",
        startTurn: 12,
        duration: 4,
        assignedMemberId: "bob",
        progress: 0,
        status: "active",
        dependencies: ["t04", "t06"],
      },
      {
        id: "t08",
        name: "結合テスト",
        phase: "テスト",
        startTurn: 14,
        duration: 4,
        assignedMemberId: "carol",
        progress: 0,
        status: "active",
        dependencies: ["t05", "t07"],
      },
      {
        id: "t09",
        name: "リリース準備",
        phase: "リリース準備",
        startTurn: 18,
        duration: 4,
        assignedMemberId: "alice",
        progress: 0,
        status: "active",
        dependencies: ["t08"],
      },
    ],
    variantId: null,
  },
  ganttVariants: {},
  conditionalEvents: [
    {
      id: "ce01",
      turn: 5,
      condition: "turn >= 5",
      eventType: "ネガティブ",
      params: {
        message: "中間チェック：進捗が遅れています",
        category: "進捗ダウン",
      },
    },
    {
      id: "ce02",
      turn: 10,
      condition: "completion_rate < 0.4",
      eventType: "ネガティブ",
      params: {
        message: "前半終了時点で進捗が40%未満です",
        category: "デバフ系",
      },
    },
    {
      id: "ce03",
      turn: 12,
      condition: "any_member_morale < 60",
      eventType: "ネガティブ",
      params: {
        message: "メンバーの士気が低下しています",
        category: "メンバー稼働系",
        targetId: null,
      },
    },
    {
      id: "ce04",
      turn: 16,
      condition: "budget_remaining <= 1500000",
      eventType: "ネガティブ",
      params: {
        message: "予算残高が150万円を下回りました",
        category: "スコープ変化系",
      },
    },
    {
      id: "ce05",
      turn: 18,
      condition: "completion_rate >= 0.8",
      eventType: "ポジティブ",
      params: {
        message: "終盤80%以上の進捗：リリースに向けて順調です",
        category: "バフ系",
      },
    },
  ],
  initialCards: ["デイリー", "レビュー", "モニタリング"],
};
