import type { BalanceConstants } from "../../src/game/schemas/balanceConstants.js";
import type { CardData } from "../../src/game/schemas/cardData.js";
import type { EventData } from "../../src/game/schemas/eventData.js";
import type { CardName } from "../../src/game/types.js";

export const testBalanceConstants: BalanceConstants = {
  GLOBAL_RULES: {
    BUFFER_RATIO: 0.25,
    TARGET_PROFIT_RATE: 0.05,
    DAILY_COST_CAP: 8,
    OVERTIME_COST_CAP: 10,
  },
  MEMBER_PARAMS: {
    SKILL: { MIN: 0, MAX: 99, INITIAL_A: 10, INITIAL_B: 8 },
    EXP: { MIN: 0 },
    MORALE: { MIN: 0, MAX: 150, INITIAL: 100 },
    HEALTH: { MIN: 0, MAX: 100, INITIAL: 100 },
    TRANSPARENCY: { MIN: 0, MAX: 150, INITIAL: 100 },
    TENSION: { MIN: 0, MAX: 150, INITIAL: 100 },
  },
  PROGRESS_DICE: {
    BASE_MIN: 3.0,
    BASE_MAX: 7.0,
  },
  EXP: {
    BASE_EXP: 10,
    LEVEL_FACTOR_MIN: 0.3,
    LEVEL_FACTOR_COEFF: 0.04,
    EDUCATION_GRANT: 30,
    PAIR_PROG_GRANT: 15,
  },
  LEVEL_UP_EXP: [
    [0, 30],
    [5, 50],
    [10, 80],
    [15, 120],
    [25, 200],
    [50, 400],
  ],
  PARAM_DELTA: {
    MORALE_NATURAL_MIN: -3,
    MORALE_NATURAL_MAX: 1,
    HEALTH_NATURAL_MIN: -3,
    HEALTH_NATURAL_MAX: -1,
    TENSION_NATURAL_DELTA: -1,
    WEEKEND_MORALE_RECOVERY: 8,
    WEEKEND_HEALTH_RECOVERY: 12,
    CHAT_MORALE_MITIGATION: 2,
    CHAT_DURATION: 3,
    ONE_ON_ONE_MORALE: 15,
    COMMENDATION_MORALE: 30,
    PLANNED_LEAVE_MORALE: 20,
    PLANNED_LEAVE_HEALTH: 25,
    EVENT_SICK_MORALE: -8,
    EVENT_SICK_HEALTH: -10,
    EVENT_REWORK_MORALE: -10,
    EVENT_STALL_MORALE: -12,
    EVENT_STALL_DEADLINE_MORALE: -20,
    EVENT_INSPIRATION_MORALE: 5,
    EVENT_REST_MORALE: 12,
    EVENT_REST_HEALTH: 10,
    EVENT_LOCAL_WIN_MORALE: 15,
  },
  THRESHOLDS: {
    MORALE_LOW_START: 60,
    MORALE_LOW_DOUBLE: 30,
    MORALE_HIGH_START: 130,
    HEALTH_LOW_START: 50,
    HEALTH_LOW_DOUBLE: 30,
    TRANSPARENCY_LOW_START: 60,
    TRANSPARENCY_HIGH_START: 130,
    TENSION_LOW_START: 60,
    TENSION_HIGH_START: 130,
    MILESTONE_FAIL_RATE: 0.9,
    PROGRESS_BOOST_LINE: 0.9,
  },
  REWORK: {
    ROLLBACK_BASE: 0.4,
    ROLLBACK_COEFF: 0.01,
  },
  STALL: {
    ONE_TURN_PROB: 0.6,
    TWO_TURN_PROB: 0.4,
    EDUCATION_STALL_TEACHER: 1,
    EDUCATION_STALL_LEARNER: 2,
    PAIR_PROG_STALL: 1,
    ONBOARDING_STALL: 3,
  },
  CHECKPOINT_PROB: {
    KICKOFF: 0.6,
    WEEKLY_MEETING: 0.5,
    WEEKLY_MEETING_SECOND: 0.3,
    MILESTONE_PASS: 0.45,
    CLOSING: 0.5,
  },
  SKILL_FACTOR_TABLE: [
    [0, [0.6, 1.2]],
    [5, [0.75, 1.15]],
    [10, [0.85, 1.1]],
    [15, [0.9, 1.08]],
    [25, [0.95, 1.05]],
  ],
  HEALTH_FACTOR_TABLE: [
    [0, [0.5, 1.0]],
    [30, [0.7, 1.0]],
    [50, [0.85, 1.0]],
    [70, [1.0, 1.0]],
  ],
};

export const testCardCostData: Record<CardName, CardData> = {
  デイリー: { cost: 1 },
  デイリー中止: { cost: 0 },
  レビュー: { cost: 1 },
  モニタリング: { cost: 1 },
  サマライズ: { cost: 1 },
  臨時MTG: { cost: 1 },
  臨時モニタリング: { cost: 1 },
  臨時サマライズ: { cost: 1 },
  教育: { cost: 2 },
  ペアプログラミング: { cost: 2 },
  雑談: { cost: 1 },
  停滞対応: { cost: 1 },
  個別面談: { cost: 2 },
  表彰: { cost: 2 },
  計画休: { cost: 2 },
  残業許可: { cost: 1 },
  アサイン: { cost: 1 },
  入れ替え: { cost: 1 },
  巻取り: { cost: 2 },
  進捗ブースト: { cost: 3 },
  強制締め: { cost: 4 },
  リスケ: { cost: 2 },
  メンバー追加: { cost: 4 },
  休出: { cost: 6 },
  納期交渉: { cost: 6 },
  スコープ交渉: { cost: 6 },
};

export const testEventProbData: Record<string, EventData> = {
  STALL: { baseProb: 0.05 },
  REWORK: { baseProb: 0.08, withDailyReviewProb: 0.05 },
  SICK: { baseProb: 0.05 },
  LOW_MOTIVATION: { baseProb: 0.06 },
  FATIGUE: { baseProb: 0.04 },
  SPEC_UNCLEAR: { baseProb: 0.05, withDailyProb: 0.03 },
  BLOCKER: { baseProb: 0.04, withDailyProb: 0.03 },
  ENV_ISSUE: { baseProb: 0.03 },
  OVER_REPORT: { baseProb: 0.04, withMonitoringProb: 0.02 },
  UNDER_REPORT: { baseProb: 0.03, withMonitoringProb: 0.01 },
  MISSING_REPORT: { baseProb: 0.03, withMonitoringProb: 0.01 },
  INSPIRATION: { baseProb: 0.03 },
  FIRST_PASS: { baseProb: 0.02 },
  REST: { baseProb: 0.03 },
  LOCAL_WIN: { baseProb: 0.02 },
};
